services:

  mypref-redis:
    image: redis:latest
    container_name: mypref-redis
    hostname: redis
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - ./data/redis:/data
    networks:
      - network
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    #command: ["redis-server"]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "PING"]
      interval: 10s
      timeout: 5s
      retries: 3
  
  mypref-redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: mypref-redis-commander
    restart: always
    #env_file:
    #- .env
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      REDIS_DB: "0"
      NO_DEFAULTS: "true"
      NO_AUTH: "true" ## works, in live use HTTP_USER and HTTP_PASSWORD instead of NO_AUTH
      #HTTP_USER: ${HTTP_USER}
      #HTTP_PASSWORD: ${HTTP_PASSWORD}
    ports:
      -  ${REDIS_COMMANDER_PORT}:8081
    depends_on:
      - mypref-redis
    networks:
      - network

  mypref-mariadb:
    image: mariadb:latest
    container_name: mypref-mariadb
    restart: always
    env_file:
    - .env
    volumes:
      - ./data/mariadb:/var/lib/mysql
    networks:
      - network
    healthcheck:
      # https://mariadb.com/kb/en/using-healthcheck-sh/
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  mypref-pma:
    image: phpmyadmin/phpmyadmin
    container_name: mypref-pma
    restart: always
    environment:
      PMA_HOST: mypref-mariadb
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      PMA_PORT: 3306
    ports:
      - ${PMA_PORT}:80
    depends_on:
      - mypref-mariadb
    networks:
      - network

  mypref-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mypref-web
    restart: always
    command: >
      sh -c "python3 manage.py collectstatic --noinput && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./pr:/app
      - ./pr/static:/app/static
    ports:
      - ${WEB_PORT}:8000
    env_file:
    - .env
    depends_on:
      # ks. https://docs.docker.com/compose/startup-order/
      mypref-mariadb:
        condition: service_healthy
      mypref-redis:
        condition: service_healthy

    networks:
      - network

networks:
  network:
    driver: bridge


# sudo chmod -R 755 ./data/db
# sudo chown -R $USER:$USER ./data/db --vist ei läinud tarvis
# docker compose run web django-admin startproject pr .
# docker-compose down
# docker-compose up -d --build  --remove-orphans

#  clear; python3 p.py > out.txt;  docker-compose down; docker-compose up -d --build --remove-orphans
# docker-compose logs web
# none-pildid maha
# docker rmi -f $(docker images -f "dangling=true" -q)
# docker rm $(docker ps -a -q)    // remove all working containers
# docker rm -f $(docker ps -a -q) // remove all containers
# docker-compose logs mypref-web
# https://www.youtube.com/watch?v=B38aDwUpcFc
# https://www.youtube.com/watch?v=c708Nf0cHrs&t=1441s
# https://www.youtube.com/watch?v=LPeerVUaqz4
